### ISSUE TITLE
Something really strange but it's not working

### ISSUE THREAD

**Issue by mnakalay** [jordanlev/c5_ajax_form#1]
Hi Jordan,
I'm using C5 5.6.0.2 and this block doesn't work in a way that I just can't explain.
It's as if the view() function from the controller was just not called at all.

None of the variables are set through $this->set() so if I try to echo any of them in the view there's no result.

And because the main array is not set than the foreach($questions as question) give the following error:
Warning: Invalid argument supplied for foreach() in...

a var_dump($questions) gives NULL

I tried it in a normal area and in a global area, same problem. I looked everywhere, I can't figure out why it does that, everything seems perfect.

**Comment by mnakalay** [comment]
I just checked and with $enablePlaceholders = true set, the javascript is not injected in the footer so it seems on_page_view() is also not called.

**Comment by mnakalay** [comment]
Forget it, it must be on my side. I tried it on ther installs of C5 5.6.0.2 and it works. I should have known, everything was by the book, no reason for an error there.

Sorry for the waste of time

**Comment by jordanlev** [comment]
heh, no worries -- I do that often myself (think there'a s problem with something but it's actually related to something else I did). If you need some help tracking down what the problem is on that one site, though... it might be related to the "Overrides Cache" (which I've had a lot of trouble with recently, in other areas of the system)? Or did you make some other customization to the form block?

**Comment by mnakalay** [comment]
Thanks for the offer but I don't think it's necessary (or even worth it). I tried it on some kind of garbage website I have with some broken installs, some "designer content" blocks designed on another install so not working...

The working version of the website takes your form perfectly so it's all good.
I'm going to go to your CRUD add-on now and see if I don't have any cunning questions to ask :)

Thanks again
