### ISSUE TITLE
After installing I get an error on any form using the form helper (including admin panels)

### ISSUE THREAD

**Issue by jacobmentalconstruct** [jordanlev/c5_ajax_form#5]
An unexpected error occurred.
Class 'Concrete5_Controller_Block_FormStatistics' not found

Any advice? I am unsure how to uninstall. Deleting it and clearing caches doesn't help.

**Comment by jordanlev** [comment]
What version of Concrete5 are you using? This was never updated for 5.7 or 5.8, so it probably won't work on the newer system. To uninstall it, you delete the folder you added when installing this in the first place (`YOURSITE/blocks/form`).

**Comment by jacobmentalconstruct** [comment]
Sorry for the delay. I was able to uninstall via the dashboard which ultimately fixed my issue. I am unclear why the uninstall button was not avail when I was first attempting that. 

If the info helps for future reference:
c5 5.7.5.8

I think I was confusing the install location. I am a new to c5 and not super familiar with the file structure. I was having trouble determining what it was using as the root from the browser point of view. For now I think I can use the functionality of the external form block. I will try this later when I am more knowledgeable. Thank you and have a great day.
